apiVersion: v1
kind: ConfigMap
metadata:
  name: is-tracker
  namespace: default
data:
  detector: |-
    {
      "camera_id" : "1",
      "broker" : "ampq://guest:guest@192.168.1.102:30000",
      "YOLO" : {
          "classes" : "/home/is-tracker/etc/data/coco.names",
          "weights" : "/home/is-tracker/etc/checkpoints/yolov3.tf",
          "tiny" : false,
          "size" : 416
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: is-tracker
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: is-tracker
  template:
    metadata:
      labels:
        app: is-tracker 
    spec:
      containers:
      - name: container-name 
        image: pedrovdsc/is-tracker:0.0.2
        command: ["python"]
        args: ["/home/is-tracker/src/is_tracker/detect_video_is_cameras.py","/opt/options/options.json"]
        resources:
          limits: 
            cpu: "2.0"
            memory: 2048Mi
        volumeMounts:
          - name: options
            mountPath: /opt/options
      volumes:
      - name: options
        configMap:
          name: is-tracker
          items:
          - key: detector
            path: options.json
